LOCATOR_RIGHT_MODULE = "//*[contains(@class,'right-module-userNameWrap')]"
LOCATOR_BALANCE = "//*[contains(@class,'js-head-balance')]"
LOCATOR_LOGOUT = "//*[@href='/logout']"
LOCATOR_LOGIN_MENU = "//*[contains(@class, 'responseHead-module-button')]"
LOCATOR_REG_FORM = "//*[contains(@class, 'authForm-module-registrationLink')]"
LOCATOR_LOGIN_BUTTON = "//*[contains(@class,'authForm-module-button')]"
LOCATOR_LOGIN_EMAIL_INPUT = "//*[contains(@class,'authForm-module-input') and contains(@class,'input-module-input')]"
LOCATOR_LOGIN_PASSWORD_INPUT = "//*[contains(@class,'authForm-module-inputPassword')]"
LOCATOR_ERROR_PASSWORD_NOTIFICATION = "//*[contains(@class, 'formMsg') and contains(@class,'js_form_msg')]"
LOCATOR_PROFILE = "//*[contains(@class, 'center-module-button') and contains(@class,'center-module-profile')]"
LOCATOR_STAT = "//*[@href='/statistics']"
LOCATOR_SURNAME_INPUT = "//*[contains(@class, 'input__inp') and contains(@class,'js-form-element')]"
LOCATOR_PRICE_LIST = "//*[@href='/segments/price_list']"
LOCATOR_SAVE_PROFILE_BUTTON = "//*[contains(@class, 'button') and contains(@class,'button_submit')]"
LOCATOR_FIO = "//*[@title='Петров Александр Александрович']"
LOCATOR_SEGMENTS = "//*[contains(@class, 'center-module-button') and contains(@class,'center-module-segments')]"
